export const Products = [
    {id: 1,
    productName: "Shoes",
    price: 100000,
    image: "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/c76e2119-acb7-4944-9085-d4f5ae2bda4a/go-flyease-easy-on-off-shoes-3svRCL.png",
    },
    {id: 2,
    productName: "Shirt",
    price: 200000,
    image: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//95/MTA-10363089/no_brand_eshal_blouse-baju_wanita-baju_kekinian_full01_rjp5x8av.jpg",
    },
    {id: 3,
    productName: "Shirt",
    price: 200000,
    image: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//95/MTA-10363089/no_brand_eshal_blouse-baju_wanita-baju_kekinian_full01_rjp5x8av.jpg",
    },
    {id: 4,
    productName: "Shirt",
    price: 200000,
    image: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//95/MTA-10363089/no_brand_eshal_blouse-baju_wanita-baju_kekinian_full01_rjp5x8av.jpg",
    },
    {id: 5,
    productName: "Shirt",
    price: 200000,
    image: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//95/MTA-10363089/no_brand_eshal_blouse-baju_wanita-baju_kekinian_full01_rjp5x8av.jpg",
    },
    {id: 6,
    productName: "Shirt",
    price: 200000,
    image: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//95/MTA-10363089/no_brand_eshal_blouse-baju_wanita-baju_kekinian_full01_rjp5x8av.jpg",
    },
]